def list_huggingface_models() -> list[str]:
    """
    List the HuggingFace model ids in the curated snapshot at
    `toki/local/models.py`.

    The snapshot is generated by the `toki-fetch-local-models` script. Note
    that the local backend accepts any HF repo id at runtime - this list only
    covers the popular subset of instruction-tuned chat models that have been
    explicitly verified.
    """
    try:
        from .models import attributes_map
    except ImportError as e:
        raise ImportError(
            "toki/local/models.py is missing - "
            "run the `toki-fetch-local-models` script to generate it."
        ) from e
    return list(attributes_map.keys())
