# DO NOT EDIT THIS FILE MANUALLY
# This file is generated via the `toki-fetch-google-models` script.

from typing import Literal
from dataclasses import dataclass


GoogleModelName = Literal[
    'gemini-2.0-flash',
    'gemini-2.0-flash-001',
    'gemini-2.0-flash-lite',
    'gemini-2.0-flash-lite-001',
    'gemini-2.5-computer-use-preview-10-2025',
    'gemini-2.5-flash',
    'gemini-2.5-flash-lite',
    'gemini-2.5-flash-lite-preview-06-17',
    'gemini-2.5-flash-lite-preview-09-2025',
    'gemini-2.5-flash-native-audio-latest',
    'gemini-2.5-flash-native-audio-preview-09-2025',
    'gemini-2.5-flash-native-audio-preview-12-2025',
    'gemini-2.5-flash-preview-09-2025',
    'gemini-2.5-pro',
    'gemini-2.5-pro-preview-tts',
    'gemini-3-flash-preview',
    'gemini-3-pro-preview',
    'gemini-3.1-flash-lite-preview',
    'gemini-3.1-flash-live-preview',
    'gemini-3.1-pro-preview',
    'gemini-3.1-pro-preview-customtools',
    'gemini-exp-1114',
    'gemini-exp-1206',
    'gemini-flash-latest',
    'gemini-flash-lite-latest',
    'gemini-gemma-2-27b-it',
    'gemini-gemma-2-9b-it',
    'gemini-pro-latest',
    'gemini-robotics-er-1.5-preview',
    'gemma-3-27b-it',
    'learnlm-1.5-pro-experimental',
    'lyria-3-clip-preview',
    'lyria-3-pro-preview'
]


@dataclass
class Attr:
    context_size: int
    supports_tools: bool
    supports_thinking: bool
    # TBD: may add more in the future


attributes_map: dict[GoogleModelName, Attr] = {
    "gemini-2.0-flash":                                         Attr(context_size=1048576, supports_tools=True, supports_thinking=False),
    "gemini-2.0-flash-001":                                     Attr(context_size=1048576, supports_tools=True, supports_thinking=False),
    "gemini-2.0-flash-lite":                                    Attr(context_size=1048576, supports_tools=True, supports_thinking=False),
    "gemini-2.0-flash-lite-001":                                Attr(context_size=1048576, supports_tools=True, supports_thinking=False),
    "gemini-2.5-computer-use-preview-10-2025":                  Attr(context_size=128000, supports_tools=True, supports_thinking=False),
    "gemini-2.5-flash":                                         Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-2.5-flash-lite":                                    Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-2.5-flash-lite-preview-06-17":                      Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-2.5-flash-lite-preview-09-2025":                    Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-2.5-flash-native-audio-latest":                     Attr(context_size=1048576, supports_tools=False, supports_thinking=False),
    "gemini-2.5-flash-native-audio-preview-09-2025":            Attr(context_size=1048576, supports_tools=False, supports_thinking=False),
    "gemini-2.5-flash-native-audio-preview-12-2025":            Attr(context_size=1048576, supports_tools=False, supports_thinking=False),
    "gemini-2.5-flash-preview-09-2025":                         Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-2.5-pro":                                           Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-2.5-pro-preview-tts":                               Attr(context_size=1048576, supports_tools=True, supports_thinking=False),
    "gemini-3-flash-preview":                                   Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-3-pro-preview":                                     Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-3.1-flash-lite-preview":                            Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-3.1-flash-live-preview":                            Attr(context_size=131072, supports_tools=True, supports_thinking=False),
    "gemini-3.1-pro-preview":                                   Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-3.1-pro-preview-customtools":                       Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-exp-1114":                                          Attr(context_size=1048576, supports_tools=True, supports_thinking=False),
    "gemini-exp-1206":                                          Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-flash-latest":                                      Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-flash-lite-latest":                                 Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-gemma-2-27b-it":                                    Attr(context_size=8192, supports_tools=True, supports_thinking=False),
    "gemini-gemma-2-9b-it":                                     Attr(context_size=8192, supports_tools=True, supports_thinking=False),
    "gemini-pro-latest":                                        Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemini-robotics-er-1.5-preview":                           Attr(context_size=1048576, supports_tools=True, supports_thinking=True),
    "gemma-3-27b-it":                                           Attr(context_size=131072, supports_tools=True, supports_thinking=False),
    "learnlm-1.5-pro-experimental":                             Attr(context_size=32767, supports_tools=True, supports_thinking=False),
    "lyria-3-clip-preview":                                     Attr(context_size=131072, supports_tools=False, supports_thinking=False),
    "lyria-3-pro-preview":                                      Attr(context_size=131072, supports_tools=False, supports_thinking=False)
}
