# DO NOT EDIT THIS FILE MANUALLY
# This file is generated via the `toki-fetch-google-models` script.

from typing import Literal
from dataclasses import dataclass


GoogleModelName = Literal[
    'gemini-2.5-flash-native-audio-latest',
    'gemini-2.5-flash-native-audio-preview-09-2025',
    'gemini-2.5-flash-native-audio-preview-12-2025',
    'gemini-3.1-flash-live-preview',
    'gemini-exp-1206',
    'gemini-flash-latest',
    'gemini-flash-lite-latest',
    'gemini-pro-latest',
    'gemini/gemini-2.0-flash',
    'gemini/gemini-2.0-flash-001',
    'gemini/gemini-2.0-flash-lite',
    'gemini/gemini-2.0-flash-lite-001',
    'gemini/gemini-2.5-computer-use-preview-10-2025',
    'gemini/gemini-2.5-flash',
    'gemini/gemini-2.5-flash-lite',
    'gemini/gemini-2.5-flash-lite-preview-06-17',
    'gemini/gemini-2.5-flash-lite-preview-09-2025',
    'gemini/gemini-2.5-flash-native-audio-latest',
    'gemini/gemini-2.5-flash-native-audio-preview-09-2025',
    'gemini/gemini-2.5-flash-native-audio-preview-12-2025',
    'gemini/gemini-2.5-flash-preview-09-2025',
    'gemini/gemini-2.5-pro',
    'gemini/gemini-2.5-pro-preview-tts',
    'gemini/gemini-3-flash-preview',
    'gemini/gemini-3-pro-preview',
    'gemini/gemini-3.1-flash-lite-preview',
    'gemini/gemini-3.1-flash-live-preview',
    'gemini/gemini-3.1-pro-preview',
    'gemini/gemini-3.1-pro-preview-customtools',
    'gemini/gemini-exp-1114',
    'gemini/gemini-exp-1206',
    'gemini/gemini-flash-latest',
    'gemini/gemini-flash-lite-latest',
    'gemini/gemini-gemma-2-27b-it',
    'gemini/gemini-gemma-2-9b-it',
    'gemini/gemini-pro-latest',
    'gemini/gemini-robotics-er-1.5-preview',
    'gemini/gemma-3-27b-it',
    'gemini/learnlm-1.5-pro-experimental',
    'gemini/lyria-3-clip-preview',
    'gemini/lyria-3-pro-preview'
]


@dataclass
class Attr:
    context_size: int
    supports_tools: bool
    # TBD: may add more in the future


attributes_map: dict[GoogleModelName, Attr] = {
    "gemini-2.5-flash-native-audio-latest":                     Attr(context_size=1048576, supports_tools=False),
    "gemini-2.5-flash-native-audio-preview-09-2025":            Attr(context_size=1048576, supports_tools=False),
    "gemini-2.5-flash-native-audio-preview-12-2025":            Attr(context_size=1048576, supports_tools=False),
    "gemini-3.1-flash-live-preview":                            Attr(context_size=131072, supports_tools=True),
    "gemini-exp-1206":                                          Attr(context_size=1048576, supports_tools=True),
    "gemini-flash-latest":                                      Attr(context_size=1048576, supports_tools=True),
    "gemini-flash-lite-latest":                                 Attr(context_size=1048576, supports_tools=True),
    "gemini-pro-latest":                                        Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.0-flash":                                  Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.0-flash-001":                              Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.0-flash-lite":                             Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.0-flash-lite-001":                         Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-computer-use-preview-10-2025":           Attr(context_size=128000, supports_tools=True),
    "gemini/gemini-2.5-flash":                                  Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-flash-lite":                             Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-flash-lite-preview-06-17":               Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-flash-lite-preview-09-2025":             Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-flash-native-audio-latest":              Attr(context_size=1048576, supports_tools=False),
    "gemini/gemini-2.5-flash-native-audio-preview-09-2025":     Attr(context_size=1048576, supports_tools=False),
    "gemini/gemini-2.5-flash-native-audio-preview-12-2025":     Attr(context_size=1048576, supports_tools=False),
    "gemini/gemini-2.5-flash-preview-09-2025":                  Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-pro":                                    Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-2.5-pro-preview-tts":                        Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-3-flash-preview":                            Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-3-pro-preview":                              Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-3.1-flash-lite-preview":                     Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-3.1-flash-live-preview":                     Attr(context_size=131072, supports_tools=True),
    "gemini/gemini-3.1-pro-preview":                            Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-3.1-pro-preview-customtools":                Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-exp-1114":                                   Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-exp-1206":                                   Attr(context_size=2097152, supports_tools=True),
    "gemini/gemini-flash-latest":                               Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-flash-lite-latest":                          Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-gemma-2-27b-it":                             Attr(context_size=8192, supports_tools=True),
    "gemini/gemini-gemma-2-9b-it":                              Attr(context_size=8192, supports_tools=True),
    "gemini/gemini-pro-latest":                                 Attr(context_size=1048576, supports_tools=True),
    "gemini/gemini-robotics-er-1.5-preview":                    Attr(context_size=1048576, supports_tools=True),
    "gemini/gemma-3-27b-it":                                    Attr(context_size=131072, supports_tools=True),
    "gemini/learnlm-1.5-pro-experimental":                      Attr(context_size=32767, supports_tools=True),
    "gemini/lyria-3-clip-preview":                              Attr(context_size=131072, supports_tools=False),
    "gemini/lyria-3-pro-preview":                               Attr(context_size=131072, supports_tools=False)
}
