import os


def get_google_api_key() -> str:
    """Retrieve the Google AI Studio API key from environment variables.

    Reads `GEMINI_API_KEY` (litellm's standard env var for the AI Studio
    `gemini/*` provider).
    """
    api_key = os.getenv('GEMINI_API_KEY')
    if not api_key:
        raise ValueError("Please set the GEMINI_API_KEY environment variable.")
    return api_key


def list_google_models() -> list[str]:
    """List the Google AI Studio model ids in the curated `toki/google/models.py` snapshot.

    The snapshot is generated by the `toki-fetch-google-models` script.
    """
    try:
        from .models import attributes_map
    except ImportError as e:
        raise ImportError(
            "toki/google/models.py is missing - "
            "run the `toki-fetch-google-models` script to generate it."
        ) from e
    return list(attributes_map.keys())
