"""Dev tooling for the OpenRouter backend.

`_create_models_types_file` regenerates the curated `toki/openrouter/models.py`
snapshot of OpenRouter models by hitting the live `/api/v1/models` endpoint.
"""

from functools import lru_cache
from os import PathLike
from pathlib import Path

import requests

from .utils import get_openrouter_api_key


here = Path(__file__).parent


@lru_cache()
def _get_openrouter_models(api_key: str) -> list[dict]:
    """Get the list of models (including all metadata) from OpenRouter API"""
    url = "https://openrouter.ai/api/v1/models"
    headers = {"Authorization": f"Bearer {api_key}"}
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        raise Exception(f"Error: {response.status_code}")

    return response.json()['data']


def _create_models_types_file(api_key: str | None = None, file: PathLike = here / 'models.py'):
    """
    Dev helper tool: create a file with a type declaration `OpenRouterModelName` containing all OpenRouter models.
    """
    if api_key is None:
        api_key = get_openrouter_api_key()
    file = Path(file)
    models = _get_openrouter_models(api_key)
    models.sort(key=lambda x: x['id'])
    model_names = [model['id'] for model in models]
    context_lengths = [model['context_length'] for model in models]
    supports_tools = ["tools" in model['supported_parameters'] for model in models]
    supports_thinking = ["reasoning" in model['supported_parameters'] for model in models]

    print(f"Creating {file.relative_to(here.parent)} with {len(models)} models")
    name_lines = ',\n    '.join(f"'{model_name}'" for model_name in model_names)
    attributes_lines = ',\n    '.join(
        f'''{f'"{model_name}":':<40}Attr(context_size={context_length}, supports_tools={supports_tool}, supports_thinking={supports_think})'''
        for model_name, context_length, supports_tool, supports_think in zip(model_names, context_lengths, supports_tools, supports_thinking)
    )
    file.write_text(f'''\
# DO NOT EDIT THIS FILE MANUALLY
# This file is generated by calling `_create_models_types_file()` in toki/openrouter/fetch_models.py
# (or via the `toki-fetch-openrouter-models` script).

from typing import Literal
from dataclasses import dataclass


OpenRouterModelName = Literal[
    {name_lines}
]


@dataclass
class Attr:
    context_size: int
    supports_tools: bool
    supports_thinking: bool
    # TBD: may add more in the future


attributes_map: dict[OpenRouterModelName, Attr] = {{
    {attributes_lines}
}}
''')
