import os


def get_openrouter_api_key() -> str:
    """Retrieve the OpenRouter API key from environment variables."""
    api_key = os.getenv('OPENROUTER_API_KEY')
    if not api_key:
        raise ValueError("Please set the OPENROUTER_API_KEY environment variable.")
    return api_key


def list_openrouter_models() -> list[str]:
    """
    List the OpenRouter model ids in the curated snapshot at
    `toki/openrouter/models.py`.

    The snapshot is generated by the `toki-fetch-openrouter-models` script.
    """
    try:
        from .models import attributes_map
    except ImportError as e:
        raise ImportError(
            "toki/openrouter/models.py is missing - "
            "run the `toki-fetch-openrouter-models` script to generate it."
        ) from e
    return list(attributes_map.keys())
