# DO NOT EDIT THIS FILE MANUALLY
# This file is generated via the `toki-fetch-anthropic-models` script.

from typing import Literal
from dataclasses import dataclass


AnthropicModelName = Literal[
    'claude-3-7-sonnet-20250219',
    'claude-3-haiku-20240307',
    'claude-3-opus-20240229',
    'claude-4-opus-20250514',
    'claude-4-sonnet-20250514',
    'claude-haiku-4-5',
    'claude-haiku-4-5-20251001',
    'claude-opus-4-1',
    'claude-opus-4-1-20250805',
    'claude-opus-4-20250514',
    'claude-opus-4-5',
    'claude-opus-4-5-20251101',
    'claude-opus-4-6',
    'claude-opus-4-6-20260205',
    'claude-opus-4-7',
    'claude-opus-4-7-20260416',
    'claude-sonnet-4-20250514',
    'claude-sonnet-4-5',
    'claude-sonnet-4-5-20250929',
    'claude-sonnet-4-6'
]


@dataclass
class Attr:
    context_size: int
    supports_tools: bool
    # TBD: may add more in the future


attributes_map: dict[AnthropicModelName, Attr] = {
    "claude-3-7-sonnet-20250219":                               Attr(context_size=200000, supports_tools=True),
    "claude-3-haiku-20240307":                                  Attr(context_size=200000, supports_tools=True),
    "claude-3-opus-20240229":                                   Attr(context_size=200000, supports_tools=True),
    "claude-4-opus-20250514":                                   Attr(context_size=200000, supports_tools=True),
    "claude-4-sonnet-20250514":                                 Attr(context_size=1000000, supports_tools=True),
    "claude-haiku-4-5":                                         Attr(context_size=200000, supports_tools=True),
    "claude-haiku-4-5-20251001":                                Attr(context_size=200000, supports_tools=True),
    "claude-opus-4-1":                                          Attr(context_size=200000, supports_tools=True),
    "claude-opus-4-1-20250805":                                 Attr(context_size=200000, supports_tools=True),
    "claude-opus-4-20250514":                                   Attr(context_size=200000, supports_tools=True),
    "claude-opus-4-5":                                          Attr(context_size=200000, supports_tools=True),
    "claude-opus-4-5-20251101":                                 Attr(context_size=200000, supports_tools=True),
    "claude-opus-4-6":                                          Attr(context_size=1000000, supports_tools=True),
    "claude-opus-4-6-20260205":                                 Attr(context_size=1000000, supports_tools=True),
    "claude-opus-4-7":                                          Attr(context_size=1000000, supports_tools=True),
    "claude-opus-4-7-20260416":                                 Attr(context_size=1000000, supports_tools=True),
    "claude-sonnet-4-20250514":                                 Attr(context_size=1000000, supports_tools=True),
    "claude-sonnet-4-5":                                        Attr(context_size=200000, supports_tools=True),
    "claude-sonnet-4-5-20250929":                               Attr(context_size=200000, supports_tools=True),
    "claude-sonnet-4-6":                                        Attr(context_size=1000000, supports_tools=True)
}
