import os


def get_anthropic_api_key() -> str:
    """Retrieve the Anthropic API key from environment variables."""
    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        raise ValueError("Please set the ANTHROPIC_API_KEY environment variable.")
    return api_key


def list_anthropic_models() -> list[str]:
    """List the Anthropic model ids in the curated `toki/anthropic/models.py` snapshot.

    The snapshot is generated by the `toki-fetch-anthropic-models` script.
    """
    try:
        from .models import attributes_map
    except ImportError as e:
        raise ImportError(
            "toki/anthropic/models.py is missing - "
            "run the `toki-fetch-anthropic-models` script to generate it."
        ) from e
    return list(attributes_map.keys())
