"""Shared codegen helpers for the litellm-backed frontends.

`fetch_provider_models(provider)` filters litellm's bundled metadata down to
chat models for one provider; `write_models_file(...)` emits the same
`Literal[...] + @dataclass Attr + attributes_map` shape that the openrouter
and local backends use.
"""

from os import PathLike
from pathlib import Path

import litellm


def fetch_provider_models(provider: str) -> list[dict]:
    """Return [{id, context_size, supports_tools}] for chat models in `provider`.

    Reads `litellm.models_by_provider` for the candidate id list and looks each
    up in `litellm.model_cost`, accepting either bare or prefixed keys. Drops
    rows that aren't chat-mode or that don't expose a context size.
    """
    raw_candidates: list[str] = list(litellm.models_by_provider.get(provider, []))
    # litellm's `models_by_provider` is inconsistent: some providers (notably
    # `gemini`) list entries already prefixed (`gemini/gemini-2.0-flash`),
    # others list bare names (`gpt-4o`). Normalize to bare names so users always
    # construct `<Provider>Model('<bare>')` and the frontend prepends the prefix.
    prefix = f"{provider}/"
    candidates = [c[len(prefix):] if c.startswith(prefix) else c for c in raw_candidates]
    out: list[dict] = []
    seen: set[str] = set()
    for bare in candidates:
        if bare in seen:
            continue
        seen.add(bare)
        info = litellm.model_cost.get(bare) or litellm.model_cost.get(f"{provider}/{bare}")
        if not info:
            continue
        if info.get("mode") != "chat":
            continue
        ctx = info.get("max_input_tokens") or info.get("max_tokens")
        if not isinstance(ctx, int):
            continue
        out.append({
            "id": bare,
            "context_size": ctx,
            "supports_tools": bool(info.get("supports_function_calling")),
        })
    out.sort(key=lambda x: x["id"])
    return out


def write_models_file(*, file: PathLike, name_alias: str, fetch_script: str, ids_with_attrs: list[dict]) -> None:
    """Write a `models.py` snapshot mirroring `toki/openrouter/models.py`'s shape.

    `name_alias` is the exported Literal type alias (e.g. 'OpenAIModelName').
    `fetch_script` is the entry-point name embedded in the do-not-edit header.
    """
    file = Path(file)
    if not ids_with_attrs:
        raise RuntimeError(f"No models found for {name_alias} - check litellm metadata")
    print(f"Writing {file} with {len(ids_with_attrs)} models")
    name_lines = ',\n    '.join(f"'{m['id']}'" for m in ids_with_attrs)
    attributes_lines = ',\n    '.join(
        f'''{f'"{m["id"]}":':<60}Attr(context_size={m["context_size"]}, supports_tools={m["supports_tools"]})'''
        for m in ids_with_attrs
    )
    file.write_text(f'''\
# DO NOT EDIT THIS FILE MANUALLY
# This file is generated via the `{fetch_script}` script.

from typing import Literal
from dataclasses import dataclass


{name_alias} = Literal[
    {name_lines}
]


@dataclass
class Attr:
    context_size: int
    supports_tools: bool
    # TBD: may add more in the future


attributes_map: dict[{name_alias}, Attr] = {{
    {attributes_lines}
}}
''')
