import os


def get_openai_api_key() -> str:
    """Retrieve the OpenAI API key from environment variables."""
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        raise ValueError("Please set the OPENAI_API_KEY environment variable.")
    return api_key


def list_openai_models() -> list[str]:
    """List the OpenAI model ids in the curated `toki/openai/models.py` snapshot.

    The snapshot is generated by the `toki-fetch-openai-models` script.
    """
    try:
        from .models import attributes_map
    except ImportError as e:
        raise ImportError(
            "toki/openai/models.py is missing - "
            "run the `toki-fetch-openai-models` script to generate it."
        ) from e
    return list(attributes_map.keys())
