def list_ollama_models() -> list[str]:
    """List the Ollama model ids in the curated `toki/ollama/models.py` snapshot.

    The snapshot is generated by the `toki-fetch-ollama-models` script. The
    ollama backend accepts any tag the daemon can pull at runtime - this list
    only covers the popular subset enumerated in the snapshot.
    """
    try:
        from .models import attributes_map
    except ImportError as e:
        raise ImportError(
            "toki/ollama/models.py is missing - "
            "run the `toki-fetch-ollama-models` script to generate it."
        ) from e
    return list(attributes_map.keys())
